# Generated by Django 6.0.8 on 2026-08-12 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('triaged', 'Triaged'), ('needs_review', 'Needs Review'), ('resolved', 'Resolved'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('workflow_id', models.CharField(blank=True, help_text='Temporal workflow ID once triage is dispatched.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TriageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('reasoning', models.TextField(blank=True)),
                ('reviewed_by_human', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage_result', to='tickets.ticket')),
            ],
        ),
    ]
